base_url = "/"

build_search_index = true

minify_html = true
generate_feed = true
compile_sass = true

taxonomies = [
    { name = "type", feed = true},
    { name = "artist", feed = true},
    { name = "director", feed = true},
    { name = "release-year", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

[extra]
favicon_url = "/favicon.png"
