[build]
base    = "."
publish = "./public"
command = "zola build"

[build.environment]
ZOLA_VERSION = "0.16.1"

# The magic for deploying previews of branches.
# We need to override the base url with whatever url Netlify assigns to our
# preview site.  We do this using the Netlify environment variable
# `$DEPLOY_PRIME_URL`.

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL --drafts"

[[redirects]]
  from = "https://tech.mitikox.top/*"
  to = "https://mitikox.top/tech/:splat"
  status = 200
  force = true
  
[[redirects]]
  from = "https://blobs.mitikox.top/*"
  to = "https://mitikox.top/blobs/:splat"
  status = 200
  force = true
