[[ServiceEvents]]
date = "2023-04-01"
megameters = 240
mechanic = "Влади"

  [[ServiceEvents.Services]]
  type = "смяна"
  part = "масло"

  [[ServiceEvents.Services]]
  type = "смяна"
  part = "филтри"

  [[ServiceEvents.Services]]
  type = "смяна"
  part = "свещи"
